pipeline{
    agent any

    parameters{
        string(name: 'ENV', defaulValue: 'uat', description: 'Mention the environment')
    }

    environment{
        GIT_REPO_URL: "https://github.com/Sagar-Soin/MY_DEVOPS-PROJECT-1.git"
        IMAGE_NAME: "my-nginx-app-jfrog"
        IMAGE_ID: "v1"
        ARTIFACTORY_URL: "https://trialfd07jy.jfrog.io/artifactory/api/docker/sagar-my-nginx-jfrog"
    }

    stages{
        stage('Checkout'){
            steps{
                git branch: 'main', url: "${env.GIT_REPO_URL}"
            }
        }
    }
}
