pipeline{
    agent any

    parameters{
        string(name: 'ENV', defaultValue: 'uat', description: 'Mention the environment')
    }

    environment{
        GIT_REPO_URL = 'https://github.com/Sagar-Soin/MY_DEVOPS-PROJECT-1.git'
        IMAGE_NAME = 'my-nginx-app-jfrog'
        IMAGE_ID = 'v1'
        ARTIFACTORY_URL = 'https://trialfd07jy.jfrog.io/artifactory/api/docker/sagar-my-nginx-jfrog'
    }

    stages{
        stage('Checkout'){
            steps{
                git branch: 'master', url: "${env.GIT_REPO_URL}"
            }
        }
        stage('ChangeDirectory & Build'){
            steps{
                dir('nginx'){
                    sh "docker build -t ${IMAGE_NAME} ."
                    sh "docker image ls | grep ${IMAGE_NAME}"
                }
            }
        }
        stage('Docker Container'){
            steps{
                sh "docker container run -d --name mynginx-jfrog -p8081:80 ${IMAGE_NAMAE}"
            }
        }
    }   
}
